version: "3.6"
services:
  redis:
    image: bitnami/redis:latest
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    healthcheck:
      test: /bin/bash -c '/usr/bin/zookeeper-shell zookeeper:2181 ls -R /brokers/ids  | /bin/grep -Eq "/brokers/ids/[0-9]+"'
      interval: 5s
      timeout: 5s
      retries: 10

  asterisk:
    build: ./asterisk
    hostname: asterisk
    ports:
      - "8088:8088"
      - "5060:5060/udp"
      - "15000-15100:15000-15100/udp"
    volumes:
      - ./asterisk/asterisk-config/:/etc/asterisk/:ro

  ari-proxy:
    image: ghcr.io/retel-io/ari-proxy:master
    hostname: ari-proxy
    volumes:
      - ./ari-proxy/ari-proxy-config/:/usr/app/config/:ro
    depends_on:
      - kafka
      - asterisk

networks:
  default:
    ipam:
      driver: default
      config:
       - subnet: 172.30.0.0/16
